use_frameworks!

platform :ios, '9.0'

target 'SCMediaBrowser_Example' do
  pod 'SCMediaBrowser', :path => '../'

  pod 'SCMediaBox', :git => 'git@github.com:Samueler/SCMediaBox.git' ,:commit=>'da04ca5'

  target 'SCMediaBrowser_Tests' do
    inherit! :search_paths

    
  end
end
